# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ex.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ex.proto',
  package='',
  serialized_pb=_b('\n\x08\x65x.proto\"\xe3\x03\n\x05Movie\x12\x0c\n\x04Name\x18\x01 \x02(\t\x12\r\n\x05\x41\x63tor\x18\x02 \x03(\t\x12\x10\n\x08\x44irector\x18\x03 \x03(\t\x12\x10\n\x08\x44uration\x18\x04 \x02(\x05\x12\x19\n\x04\x64\x61te\x18\x05 \x02(\x0b\x32\x0b.Movie.Date\x12\x1b\n\x05genre\x18\x06 \x03(\x0e\x32\x0c.Movie.Genre\x12\x1d\n\x06review\x18\x07 \x03(\x0b\x32\r.Movie.Review\x1a>\n\x04\x44\x61te\x12\x0b\n\x03\x64\x61y\x18\x01 \x02(\x05\x12\x1b\n\x05month\x18\x02 \x02(\x0e\x32\x0c.Movie.Month\x12\x0c\n\x04Year\x18\x03 \x02(\x05\x1aR\n\x06Review\x12\x0c\n\x04User\x18\x01 \x02(\t\x12\x0e\n\x06Rating\x18\x02 \x02(\x05\x12\x19\n\x04\x64\x61te\x18\x03 \x02(\x0b\x32\x0b.Movie.Date\x12\x0f\n\x07\x43omment\x18\x04 \x01(\t\"s\n\x05Month\x12\x07\n\x03Jan\x10\x01\x12\x07\n\x03\x46\x65\x62\x10\x02\x12\x07\n\x03Mar\x10\x03\x12\x07\n\x03\x41pr\x10\x04\x12\x07\n\x03May\x10\x05\x12\x07\n\x03Jun\x10\x06\x12\x07\n\x03Jul\x10\x07\x12\x07\n\x03\x41ug\x10\x08\x12\x07\n\x03Sep\x10\t\x12\x07\n\x03Oct\x10\n\x12\x07\n\x03Nov\x10\x0b\x12\x07\n\x03\x44\x65\x63\x10\x0c\"9\n\x05Genre\x12\r\n\tAdventure\x10\x00\x12\n\n\x06\x41\x63tion\x10\x01\x12\t\n\x05\x44rama\x10\x02\x12\n\n\x06\x43omedy\x10\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_MOVIE_MONTH = _descriptor.EnumDescriptor(
  name='Month',
  full_name='Movie.Month',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Jan', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Feb', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Mar', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Apr', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='May', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Jun', index=5, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Jul', index=6, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Aug', index=7, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Sep', index=8, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Oct', index=9, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Nov', index=10, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Dec', index=11, number=12,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=322,
  serialized_end=437,
)
_sym_db.RegisterEnumDescriptor(_MOVIE_MONTH)

_MOVIE_GENRE = _descriptor.EnumDescriptor(
  name='Genre',
  full_name='Movie.Genre',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Adventure', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Action', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Drama', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Comedy', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=439,
  serialized_end=496,
)
_sym_db.RegisterEnumDescriptor(_MOVIE_GENRE)


_MOVIE_DATE = _descriptor.Descriptor(
  name='Date',
  full_name='Movie.Date',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='day', full_name='Movie.Date.day', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='month', full_name='Movie.Date.month', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Year', full_name='Movie.Date.Year', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=236,
)

_MOVIE_REVIEW = _descriptor.Descriptor(
  name='Review',
  full_name='Movie.Review',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='User', full_name='Movie.Review.User', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Rating', full_name='Movie.Review.Rating', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='date', full_name='Movie.Review.date', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Comment', full_name='Movie.Review.Comment', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=320,
)

_MOVIE = _descriptor.Descriptor(
  name='Movie',
  full_name='Movie',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Name', full_name='Movie.Name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Actor', full_name='Movie.Actor', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Director', full_name='Movie.Director', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Duration', full_name='Movie.Duration', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='date', full_name='Movie.date', index=4,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='genre', full_name='Movie.genre', index=5,
      number=6, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='review', full_name='Movie.review', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_MOVIE_DATE, _MOVIE_REVIEW, ],
  enum_types=[
    _MOVIE_MONTH,
    _MOVIE_GENRE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=496,
)

_MOVIE_DATE.fields_by_name['month'].enum_type = _MOVIE_MONTH
_MOVIE_DATE.containing_type = _MOVIE
_MOVIE_REVIEW.fields_by_name['date'].message_type = _MOVIE_DATE
_MOVIE_REVIEW.containing_type = _MOVIE
_MOVIE.fields_by_name['date'].message_type = _MOVIE_DATE
_MOVIE.fields_by_name['genre'].enum_type = _MOVIE_GENRE
_MOVIE.fields_by_name['review'].message_type = _MOVIE_REVIEW
_MOVIE_MONTH.containing_type = _MOVIE
_MOVIE_GENRE.containing_type = _MOVIE
DESCRIPTOR.message_types_by_name['Movie'] = _MOVIE

Movie = _reflection.GeneratedProtocolMessageType('Movie', (_message.Message,), dict(

  Date = _reflection.GeneratedProtocolMessageType('Date', (_message.Message,), dict(
    DESCRIPTOR = _MOVIE_DATE,
    __module__ = 'ex_pb2'
    # @@protoc_insertion_point(class_scope:Movie.Date)
    ))
  ,

  Review = _reflection.GeneratedProtocolMessageType('Review', (_message.Message,), dict(
    DESCRIPTOR = _MOVIE_REVIEW,
    __module__ = 'ex_pb2'
    # @@protoc_insertion_point(class_scope:Movie.Review)
    ))
  ,
  DESCRIPTOR = _MOVIE,
  __module__ = 'ex_pb2'
  # @@protoc_insertion_point(class_scope:Movie)
  ))
_sym_db.RegisterMessage(Movie)
_sym_db.RegisterMessage(Movie.Date)
_sym_db.RegisterMessage(Movie.Review)


# @@protoc_insertion_point(module_scope)
