# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Message.proto',
  package='',
  serialized_pb=_b('\n\rMessage.proto\"\x9f\x03\n\x07Message\x12\x1f\n\x06header\x18\x01 \x02(\x0b\x32\x0f.Message.Header\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\x12\x1f\n\x06server\x18\x03 \x03(\x0e\x32\x0f.Message.Server\x12\x0b\n\x03str\x18\x04 \x03(\t\x1a?\n\x06Header\x12\x0b\n\x03uid\x18\x01 \x02(\x05\x12\x1b\n\x04type\x18\x02 \x02(\x0e\x32\r.Message.Type\x12\x0b\n\x03\x61\x63k\x18\x03 \x01(\x05\"!\n\x04Type\x12\x0b\n\x07Request\x10\x00\x12\x0c\n\x08Response\x10\x01\"\x95\x01\n\x06Opcode\x12\x0c\n\x08NewMovie\x10\x00\x12\x0c\n\x08GetMvoie\x10\x01\x12\r\n\tListMovie\x10\x02\x12\x0f\n\x0b\x46indByActor\x10\x03\x12\x12\n\x0e\x46indByDirector\x10\x04\x12\x0f\n\x0b\x44\x65leteMovie\x10\x05\x12\x0e\n\nGetReviews\x10\x06\x12\x0e\n\nAddReviews\x10\x07\x12\n\n\x06Update\x10\x08\"8\n\x06Server\x12\t\n\x05Print\x10\x00\x12\t\n\x05Reply\x10\x01\x12\x0b\n\x07Success\x10\x02\x12\x0b\n\x07\x46\x61ilure\x10\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_MESSAGE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='Message.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Request', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Response', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=190,
  serialized_end=223,
)
_sym_db.RegisterEnumDescriptor(_MESSAGE_TYPE)

_MESSAGE_OPCODE = _descriptor.EnumDescriptor(
  name='Opcode',
  full_name='Message.Opcode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NewMovie', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GetMvoie', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ListMovie', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FindByActor', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FindByDirector', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DeleteMovie', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GetReviews', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AddReviews', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Update', index=8, number=8,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=226,
  serialized_end=375,
)
_sym_db.RegisterEnumDescriptor(_MESSAGE_OPCODE)

_MESSAGE_SERVER = _descriptor.EnumDescriptor(
  name='Server',
  full_name='Message.Server',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Print', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Reply', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Success', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Failure', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=377,
  serialized_end=433,
)
_sym_db.RegisterEnumDescriptor(_MESSAGE_SERVER)


_MESSAGE_HEADER = _descriptor.Descriptor(
  name='Header',
  full_name='Message.Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='Message.Header.uid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='Message.Header.type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ack', full_name='Message.Header.ack', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=188,
)

_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='Message.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='command', full_name='Message.command', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='server', full_name='Message.server', index=2,
      number=3, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='str', full_name='Message.str', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_MESSAGE_HEADER, ],
  enum_types=[
    _MESSAGE_TYPE,
    _MESSAGE_OPCODE,
    _MESSAGE_SERVER,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=433,
)

_MESSAGE_HEADER.fields_by_name['type'].enum_type = _MESSAGE_TYPE
_MESSAGE_HEADER.containing_type = _MESSAGE
_MESSAGE.fields_by_name['header'].message_type = _MESSAGE_HEADER
_MESSAGE.fields_by_name['server'].enum_type = _MESSAGE_SERVER
_MESSAGE_TYPE.containing_type = _MESSAGE
_MESSAGE_OPCODE.containing_type = _MESSAGE
_MESSAGE_SERVER.containing_type = _MESSAGE
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(

  Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), dict(
    DESCRIPTOR = _MESSAGE_HEADER,
    __module__ = 'Message_pb2'
    # @@protoc_insertion_point(class_scope:Message.Header)
    ))
  ,
  DESCRIPTOR = _MESSAGE,
  __module__ = 'Message_pb2'
  # @@protoc_insertion_point(class_scope:Message)
  ))
_sym_db.RegisterMessage(Message)
_sym_db.RegisterMessage(Message.Header)


# @@protoc_insertion_point(module_scope)
